@baseUrl=http://localhost:3333

###Register User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "firstName": "francesco",
    "lastName" : "di corpo",
    "email": "francesco@hotmail.com",
    "password": "password"
}