@baseUrl=http://localhost:3333

###Register User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "firstName": "francesco",
    "lastName" : "di corpo",
    "email": "francesco2@hotmail.com",
    "password": "password"
}

###Login User
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "francesco2@hotmail.com",
    "password": "password"
}


###create Activities
POST {{baseUrl}}/api/activities
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMjY3MzUzMn0.-QKcZiGrrbnXzdEf6YWF0aGDNHLvT6-uESUF8SMYKeM

{
    "title": "prov",
    "status":"TODO",
    "expirationDate":"2024-06-25T23:37:04.271Z",
    "description":"descrizione test-12"  
}

###get All Activities
GET {{baseUrl}}/api/activities?status=cancelled
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMjY3MzUzMn0.-QKcZiGrrbnXzdEf6YWF0aGDNHLvT6-uESUF8SMYKeM


###get Activity by id
GET {{baseUrl}}/api/activities/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjY3ODM5M30.IxFvTnUNG8ZSRCMWZE079GH423YZOQaBFy8Tp7KHKsQ


###update Activity
PUT  {{baseUrl}}/api/activities/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMjY3OTU4NH0.IxKacSlJCiqQybqW4PHLuGefSTvZUWrYFHBQOgFgiho
Content-Type: application/json

{
    "title": "test update"

}


###delete Activity
DELETE {{baseUrl}}/api/activities/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMjY4MDMwOH0.s5xODtBQWrc--3oLZC0-kyipVba-ofb5vWlhN7hzcwU